// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfozelfdjlaaeihpuruz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhmb3plbGZkamxhYWVpaHB1cnV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NzI4NzUsImV4cCI6MjA3MzU0ODg3NX0.V31e9PIS2x4nFhHp6OL0-Gscfgq7r0EXbs6NRgO54n0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});